version: '3.8'

services:
  balance-service:
    restart: always
    build: ./
    command: ./scripts/wait-for-postgres.sh db ./balance
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DB_PASSWORD=${PG_PASSWORD}
      - COMPOSE=true
  db:
    restart: always
    image: postgres:latest
    volumes:
    - ././database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    ports:
      - 5432:5432